function sing () {
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.playTone(392, music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 1)
    music.playTone(440, music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P2, 0)
    pins.digitalWritePin(DigitalPin.P8, 1)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P8, 0)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P8, 1)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    pins.digitalWritePin(DigitalPin.P8, 0)
    music.rest(music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P12, 1)
    music.playTone(392, music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P12, 0)
    pins.digitalWritePin(DigitalPin.P13, 1)
    music.playTone(440, music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P13, 0)
    pins.digitalWritePin(DigitalPin.P14, 1)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P14, 0)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P14, 1)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P14, 0)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P15, 1)
    music.playTone(392, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P15, 0)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P15, 1)
    music.playTone(392, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P15, 0)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P16, 1)
    music.playTone(392, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P16, 0)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P16, 1)
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Sixteenth))
    pins.digitalWritePin(DigitalPin.P16, 0)
    music.playTone(262, music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P16, 1)
    music.rest(music.beat(BeatFraction.Whole))
    pins.digitalWritePin(DigitalPin.P16, 0)
    music.rest(music.beat(BeatFraction.Whole))
    basic.pause(5000)
}
let l = 0
music.setVolume(3)
basic.forever(function () {
    if (pins.analogReadPin(AnalogPin.P1) - l > 10) {
        sing()
    }
    l = pins.analogReadPin(AnalogPin.P1)
    basic.pause(2000)
})
